mod_id=frieren_flight
mod_name=Frieren Flight - Iron's Spells Addon
mod_license=AGPL-3.0
mod_version=1.0.0
mod_group=com.frierenflight
mod_authors=Aling7788565
mod_description=Frieren-inspired Flight Magic (人類の魔法) for Iron's Spells 'n Spellbooks.

minecraft_version_neoforge=1.21.1
neoforge_version=21.1.248
irons_spellbooks_version_neoforge=1.21.1-3.16.3

minecraft_version_forge=1.20.1
forge_version=47.3.0
irons_spellbooks_version_forge=1.20.1-3.16.2
