pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.minecraftforge.net' }
    }
}

rootProject.name = 'frieren_flight'

include 'common'
include 'neoforge'
include 'forge'
